version: '3.8'

services:
  php-apache:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - monreseau

  db:
    image: mariadb:10.5
    container_name: mariadb-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mon_site
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - monreseau

volumes:
  mariadb_data:

networks:
  monreseau:
