services:
  php-apache:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - db
    networks:
      - monreseau

  db:
    image: mariadb:10.5
    ports:
      - "3307:3307"
    container_name: mariadb-prod-3307
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mon_site_prod
      MYSQL_USER: user_prod
      MYSQL_PASSWORD: pass_prod
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - monreseau

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-prod
    restart: always
    ports:
      - "8092:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=32M
    depends_on:
      - db
    networks:
      - monreseau
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini

volumes:
  mariadb_data:

networks:
  monreseau:
