version: '3.9'

services:
  php-apache:
    build:
      context: .. # Prend la racine du projet, comme en prod
      dockerfile: docker/web/Dockerfile
    container_name: php-apache-dev
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ../:/var/www
    environment:
      APP_ENV: dev
    networks:
      - monreseau-dev
      
  db:
    image: mariadb:10.5
    container_name: mariadb-dev
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mon_site_dev
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: pass_dev
    volumes:
      - mariadb_data_dev:/var/lib/mysql
    networks:
      - monreseau-dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-dev
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=32M
    depends_on:
      - db
    volumes:
      - ../php.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - monreseau-dev

volumes:
  mariadb_data_dev:

networks:
  monreseau-dev:


